### ISSUE TITLE
得不到账号密码

### ISSUE THREAD

**Issue by and-ksi** [tjuyy/ZXHN-F650-crack#1]
设备类型GPON天翼网关(4口单频)
产品型号ZXHN F650
软件版本号V2.0.0P1T3

采集出来的文件：
                                              <HTML>
                                              <HEAD><TITLE>404 Not Found</TITLE></HEAD>
                                              <BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#2020ff" VLINK="#4040cc">
                                              <H2>404 Not Found</H2>
The requested URL '/db_user_cfg.xml' was not found on this server.
                                          <HR>
                                          <ADDRESS><A HREF="http://www.zte.com.cn">Mini web server 1.0 ZTE corp 2005.</A></ADDRESS>
                                          </BODY>
                                          </HTML>

我是通过ubuntu虚拟机python3跑的程序，会不会是这个原因呢？

**Comment by and-ksi** [comment]
文件只有几行，上面被自动转成markdown了，我的虚拟机网络是桥接模式，应该是没问题的.....感觉电信又更新软件了？

已将原始配置文件保存到本地 db_user_cfg.xml
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    cracked_bytes = unPack(f)
  File "main.py", line 22, in unPack
    unpacked_bytes += zlib.decompress(data)  # return decompress byteswap   
zlib.error: Error -3 while decompressing data: incorrect header check

这里是ubuntu的输出，因为文件里啥都没有。似乎是文件位置或者名称更改了？

**Comment by and-ksi** [comment]
找到了另外的方式，https://www.52pojie.cn/forum.php?mod=viewthread&tid=1224435&highlight=F650，无论如何，感谢大佬的代码。
